name: Manual NuGet Publish

# workflow_dispatch is used to manually invoke the GH action
on: [workflow_dispatch]

env:
  # Setting the required env flags
  config: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  dotnet_core_version: 6.0.x

jobs:
  publish_job:
  # CI running on linux
    runs-on: ubuntu-latest

    steps:
    # This step clones the source code to the CI build machine
    - name: Checkout code
      uses: actions/checkout@v2

    # This step installs the .NET SDK
    - name: Install .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_core_version }}

    # Run dotnet pack to create the nupkg file for the project and store in artifacts folder
    - name: Run Pack on EventFeed
      run: dotnet pack src/EventFeed/EventFeed.fsproj -o ./artifacts --configuration ${{ env.config }}
      shell: bash

    - name: Run Pack on EventFeed.Producer.MSSQL
      run: dotnet pack src/EventFeed.Producer.MSSQL/EventFeed.Producer.MSSQL.fsproj -o ./artifacts --configuration ${{ env.config }}
      shell: bash

    - name: Run Pack on EventFeed.AspNetCore
      run: dotnet pack src/EventFeed.AspNetCore/EventFeed.AspNetCore.fsproj -o ./artifacts --configuration ${{ env.config }}
      shell: bash

    # Find all the created nupkg files and publish it to NuGet, we use the wonderful swiss-army knife capability `find -exec` to find and then execute an action on it.
    # NUGET_DEPLOY_KEY is the NuGet API key stored in the repo GH action secrets
    # If you also publish symbol packages, find the snupkg files and publish it to NuGet
    # One problem with this approach is failures to publish to not fail the workflow :/
    - name: Publish to NuGet
      run: |
        find . -name '*.nupkg' -exec dotnet nuget push "{}" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_DEPLOY_KEY }} --skip-duplicate \;
        find . -name '*.snupkg' -exec dotnet nuget push "{}" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_DEPLOY_KEY }} --skip-duplicate \;
      shell: bash